/** Every string the Activity panel shows (Underspire's copy, sentence case; CSS uppercases where the style asks). */
export const C = {
  title: 'Activity',
  region: 'Staff Activity',
  openCommand: 'Activity: open the panel',
  categoryGroup: 'Activity category',
  scopeGroup: 'Activity scope',
  categories: [
    { id: 'all', label: 'All' },
    { id: 'text', label: 'Text' },
    { id: 'looc', label: 'LOOC' },
    { id: 'npc', label: 'NPC' },
  ] as const,
  global: 'Global',
  watched: 'Watched',
  filter: 'Filter activity',
  filterPlaceholder: 'Filter activity…',
  watchToggle: (n: number) => `Watch (${n})`,
  watchFind: 'Find a character, NPC or location to watch',
  watchFindPlaceholder: 'Name or #id to watch…',
  searching: 'Searching…',
  noMatch: 'No matching character, NPC or location.',
  watchHint: 'Watch any character, NPC or location by name or #id.',
  resultMeta: (id: string, kind: string) => `#${id.replace(/^#/, '')} · ${kind}`,
  watch: 'Watch',
  unwatch: 'Unwatch',
  unwatchLabel: (label: string) => `Unwatch ${label}`,
  watchName: (on: boolean, name: string) => `${on ? 'Unwatch' : 'Watch'} ${name}`,
  watchLocation: (on: boolean) => `${on ? 'Unwatch' : 'Watch'} location`,
  addPuppet: 'Add puppet',
  inPuppets: 'In puppets',
  puppetFor: (label: string, name: string, many: boolean) => (many ? `${label}: ${name}` : label),
  retry: 'Retry',
  gap: 'Some activity was missed.',
  dismiss: 'Dismiss',
  rolledOut: 'Paused activity has rolled out of the feed.',
  loading: 'Loading activity…',
  pausedEmpty: 'Feed paused. Resume to see new activity.',
  noWatches: 'Add a watch to see activity for a character or location.',
  noMatchFilters: 'No activity matches these filters.',
  waiting: 'New player activity will appear here.',
  unknown: 'Unknown',
  kind: (k: string) => (k.startsWith('handset.') ? 'Text' : k === 'looc' ? 'LOOC' : 'NPC'),
  status: (paused: boolean, following: boolean, n: number) => `${paused ? 'Paused' : following ? 'Following' : 'Reading'} · ${n} shown`,
  latest: (n: number) => `Latest (${n})`,
  pause: 'Pause',
  resume: 'Resume',
  // Errors the panel shows (the game's own error text is shown as sent).
  noAnswer: 'The game did not answer.',
  noGmcp: 'This connection cannot send GMCP.',
  notAllowed: 'Activity is not available to this character.',
};
